[package]
name = "linx"
version = "1.0.0"
edition = "2024"
description = "Self-hosted URL shortener."
license = "MIT"
authors = ["Jeremy Ibanez"]
repository = "https://github.com/j1banez/linx"
homepage = "https://github.com/j1banez/linx"

[dependencies]
askama = "0.15.4"
axum = "0.8.8"
lru = "0.16.3"
rand = "0.8"
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
url = "2.5.8"

[dev-dependencies]
http-body-util = "0.1"
tower = "0.5"

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
perf = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
manual_range_contains = "allow"
missing_errors_doc = "allow"
undocumented_unsafe_blocks = "deny"
dbg_macro = "warn"
#expect_used = "warn"
if_then_some_else_none = "warn"
indexing_slicing = "warn"
large_include_file = "warn"
print_stderr = "warn"
print_stdout = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
unnecessary_safety_doc = "warn"
#unwrap_used = "warn"
module_name_repetitions = "allow"
